# Copyright (c) 2024, Fonden Mærsk Mc-Kinney Møller Center for Zero Carbon Shipping
#
# This file is part of NavigaTE.
#
# NavigaTE is a free software: you can modify it under the
# terms of the full license agreement found in the LICENSE
# file located in the root directory of this source tree.

Tank "main_compressed_hydrogen_gas_carrier_100k_cbm" {
	FuelTypes=[HYDROGEN]
    Size=2000
	
	CAPEX = 675
	OPEX = 6.75 
}
