# Copyright (c) 2024, Fonden Mærsk Mc-Kinney Møller Center for Zero Carbon Shipping
#
# This file is part of NavigaTE.
#
# NavigaTE is a free software: you can modify it under the
# terms of the full license agreement found in the LICENSE
# file located in the root directory of this source tree.

Tank "main_methane_container_15000_teu" {
	FuelTypes=[METHANE]
	Size=15000
	
	CAPEX = 1350
	OPEX = 13.5 
}
