# Copyright (c) 2024, Fonden Mærsk Mc-Kinney Møller Center for Zero Carbon Shipping
#
# This file is part of NavigaTE.
#
# NavigaTE is a free software: you can modify it under the
# terms of the full license agreement found in the LICENSE
# file located in the root directory of this source tree.

Tank "main_oil_container_3500_teu" {
	FuelTypes=[HFO, DIESEL]
	Size=3500
	
	CAPEX = 140
	OPEX = 1.4 
}
