# Copyright (c) 2024, Fonden Mærsk Mc-Kinney Møller Center for Zero Carbon Shipping
#
# This file is part of NavigaTE.
#
# NavigaTE is a free software: you can modify it under the
# terms of the full license agreement found in the LICENSE
# file located in the root directory of this source tree.

Tank "main_FTdiesel_gas_carrier_100k_cbm" {
	FuelTypes=[DIESEL]
    Size=2273.833588921418
	
	CAPEX = 140
	OPEX = 1.4 
}
