# Copyright (c) 2024, Fonden Mærsk Mc-Kinney Møller Center for Zero Carbon Shipping
#
# This file is part of NavigaTE.
#
# NavigaTE is a free software: you can modify it under the
# terms of the full license agreement found in the LICENSE
# file located in the root directory of this source tree.

Tank "main_methanol_bulk_carrier_panamax" {
	FuelTypes=[METHANOL]
	Size=3000
	
	CAPEX = 215
	OPEX = 2.15 
}
