############################# Bulk carriers ###################################

# Ammonia
Import Vessel "bulk_carrier_capesize_ice_ammonia"
Vessel "bulk_carrier_capesize_ice_ammonia" {
        EnforceMainFuelShare = TRUE
}

Import Vessel "bulk_carrier_panamax_ice_ammonia"
Vessel "bulk_carrier_panamax_ice_ammonia" {
        EnforceMainFuelShare = TRUE
}

Import Vessel "bulk_carrier_handy_ice_ammonia"
Vessel "bulk_carrier_handy_ice_ammonia" {
        EnforceMainFuelShare = TRUE
}

############################# Container ships ###################################

# Ammonia
Import Vessel "container_15000_teu_ice_ammonia"
Vessel "container_15000_teu_ice_ammonia" {
        EnforceMainFuelShare = TRUE
}

Import Vessel "container_8000_teu_ice_ammonia"
Vessel "container_8000_teu_ice_ammonia" {
        EnforceMainFuelShare = TRUE
}

Import Vessel "container_3500_teu_ice_ammonia"
Vessel "container_3500_teu_ice_ammonia" {
        EnforceMainFuelShare = TRUE
}

############################# Tankers ###################################

# Ammonia
Import Vessel "tanker_300k_dwt_ice_ammonia"
Vessel "tanker_300k_dwt_ice_ammonia" {
        EnforceMainFuelShare = TRUE
}

Import Vessel "tanker_100k_dwt_ice_ammonia"
Vessel "tanker_100k_dwt_ice_ammonia" {
        EnforceMainFuelShare = TRUE
}

Import Vessel "tanker_35k_dwt_ice_ammonia"
Vessel "tanker_35k_dwt_ice_ammonia" {
        EnforceMainFuelShare = TRUE
}

######################### Gas Carriers ###########################

# Ammonia
Import Vessel "gas_carrier_100k_cbm_ice_ammonia"
Vessel "gas_carrier_100k_cbm_ice_ammonia" {
        EnforceMainFuelShare = TRUE
}
