############################# Bulk carriers ###################################

# Methanol
Import Vessel "bulk_carrier_capesize_ice_methanol"
Vessel "bulk_carrier_capesize_ice_methanol" {
        NominalCapacity = 132698.57214502685
        EnforceMainFuelShare = TRUE
}

Import Vessel "bulk_carrier_panamax_ice_methanol"
Vessel "bulk_carrier_panamax_ice_methanol" {
        NominalCapacity = 58027.416176561645
        EnforceMainFuelShare = TRUE
}

Import Vessel "bulk_carrier_handy_ice_methanol"
Vessel "bulk_carrier_handy_ice_methanol" {
        NominalCapacity = 18475.353646040214
        EnforceMainFuelShare = TRUE
}

############################# Container ships ###################################

# Methanol
Import Vessel "container_15000_teu_ice_methanol"
Vessel "container_15000_teu_ice_methanol" {
        NominalCapacity = 14063.64963841033
        EnforceMainFuelShare = TRUE
}

Import Vessel "container_8000_teu_ice_methanol"
Vessel "container_8000_teu_ice_methanol" {
        NominalCapacity = 7438.1897830461985
        EnforceMainFuelShare = TRUE
}

Import Vessel "container_3500_teu_ice_methanol"
Vessel "container_3500_teu_ice_methanol" {
        NominalCapacity = 3281.5182489624103
        EnforceMainFuelShare = TRUE
}

############################# Tankers ###################################

# Methanol
Import Vessel "tanker_300k_dwt_ice_methanol"
Vessel "tanker_300k_dwt_ice_methanol" {
        NominalCapacity = 272491.91986837843
        EnforceMainFuelShare = TRUE
}

Import Vessel "tanker_100k_dwt_ice_methanol"
Vessel "tanker_100k_dwt_ice_methanol" {
        NominalCapacity = 90266.34056283507
        EnforceMainFuelShare = TRUE
}

Import Vessel "tanker_35k_dwt_ice_methanol"
Vessel "tanker_35k_dwt_ice_methanol" {
        NominalCapacity = 29947.634457764638
        EnforceMainFuelShare = TRUE
}

######################### Gas Carriers ###########################

# Methanol
Import Vessel "gas_carrier_100k_cbm_ice_methanol"
Vessel "gas_carrier_100k_cbm_ice_methanol" {
        NominalCapacity = 95220.86775444633
        EnforceMainFuelShare = TRUE
}
