Import Vessel "bulk_carrier_capesize_ice_oil"
Vessel "bulk_carrier_capesize_ice_oil" {
        Route=Route("singapore_rotterdam_bulk_carrier_capesize")
        NominalCapacity = 140077.8522122301
}

Import Vessel "bulk_carrier_panamax_ice_oil"
Vessel "bulk_carrier_panamax_ice_oil" {
        Route=Route("singapore_rotterdam_bulk_carrier_panamax")
        NominalCapacity = 62001.708506750336
}

Import Vessel "bulk_carrier_handy_ice_oil"
Vessel "bulk_carrier_handy_ice_oil" {
        Route=Route("singapore_rotterdam_bulk_carrier_handy")
        NominalCapacity = 21573.978761473172
}

Import Vessel "bulk_carrier_capesize_ice_liquid_hydrogen"
Vessel "bulk_carrier_capesize_ice_liquid_hydrogen" {
        Route=Route("singapore_rotterdam_bulk_carrier_capesize")
        NominalCapacity = 102190.38268173016
}

Import Vessel "bulk_carrier_panamax_ice_liquid_hydrogen"
Vessel "bulk_carrier_panamax_ice_liquid_hydrogen" {
        Route=Route("singapore_rotterdam_bulk_carrier_panamax")
        NominalCapacity = 39568.95844340046
}

Import Vessel "bulk_carrier_handy_ice_liquid_hydrogen"
Vessel "bulk_carrier_handy_ice_liquid_hydrogen" {
        Route=Route("singapore_rotterdam_bulk_carrier_handy")
        NominalCapacity = 1000.0
}

Import Vessel "bulk_carrier_capesize_ice_ammonia"
Vessel "bulk_carrier_capesize_ice_ammonia" {
        Route=Route("singapore_rotterdam_bulk_carrier_capesize")
        NominalCapacity = 128365.56658063084
}

Import Vessel "bulk_carrier_panamax_ice_ammonia"
Vessel "bulk_carrier_panamax_ice_ammonia" {
        Route=Route("singapore_rotterdam_bulk_carrier_panamax")
        NominalCapacity = 55478.56782353357
}

Import Vessel "bulk_carrier_handy_ice_ammonia"
Vessel "bulk_carrier_handy_ice_ammonia" {
        Route=Route("singapore_rotterdam_bulk_carrier_handy")
        NominalCapacity = 16522.523177286264
}

Import Vessel "bulk_carrier_capesize_ice_methanol"
Vessel "bulk_carrier_capesize_ice_methanol" {
        Route=Route("singapore_rotterdam_bulk_carrier_capesize")
        NominalCapacity = 132698.57214502685
}

Import Vessel "bulk_carrier_panamax_ice_methanol"
Vessel "bulk_carrier_panamax_ice_methanol" {
        Route=Route("singapore_rotterdam_bulk_carrier_panamax")
        NominalCapacity = 58027.416176561645
}

Import Vessel "bulk_carrier_handy_ice_methanol"
Vessel "bulk_carrier_handy_ice_methanol" {
        Route=Route("singapore_rotterdam_bulk_carrier_handy")
        NominalCapacity = 18475.353646040214
}

Import Vessel "bulk_carrier_capesize_ice_FTdiesel"
Vessel "bulk_carrier_capesize_ice_FTdiesel" {
        Route=Route("singapore_rotterdam_bulk_carrier_capesize")
        NominalCapacity = 139741.85883622992
}

Import Vessel "bulk_carrier_panamax_ice_FTdiesel"
Vessel "bulk_carrier_panamax_ice_FTdiesel" {
        Route=Route("singapore_rotterdam_bulk_carrier_panamax")
        NominalCapacity = 61913.724937707535
}

Import Vessel "bulk_carrier_handy_ice_FTdiesel"
Vessel "bulk_carrier_handy_ice_FTdiesel" {
        Route=Route("singapore_rotterdam_bulk_carrier_handy")
        NominalCapacity = 21419.991691055973
}

Import Vessel "bulk_carrier_capesize_ice_methane"
Vessel "bulk_carrier_capesize_ice_methane" {
        Route=Route("singapore_rotterdam_bulk_carrier_capesize")
        NominalCapacity = 134865.1809056272
}

Import Vessel "bulk_carrier_panamax_ice_methane"
Vessel "bulk_carrier_panamax_ice_methane" {
        Route=Route("singapore_rotterdam_bulk_carrier_panamax")
        NominalCapacity = 59369.038826797136
}

Import Vessel "bulk_carrier_handy_ice_methane"
Vessel "bulk_carrier_handy_ice_methane" {
        Route=Route("singapore_rotterdam_bulk_carrier_handy")
        NominalCapacity = 19321.736324303154
}

