############################# Bulk carriers ###################################

# LSFO
Import Vessel "bulk_carrier_capesize_ice_oil"
Vessel "bulk_carrier_capesize_ice_oil" {
        Route=Route("singapore_rotterdam_bulk_carrier_capesize")
        NominalCapacity = 140077.8522122301
}

Import Vessel "bulk_carrier_panamax_ice_oil"
Vessel "bulk_carrier_panamax_ice_oil" {
        Route=Route("singapore_rotterdam_bulk_carrier_panamax")
        NominalCapacity = 62001.708506750336
}

Import Vessel "bulk_carrier_handy_ice_oil"
Vessel "bulk_carrier_handy_ice_oil" {
        Route=Route("singapore_rotterdam_bulk_carrier_handy")
        NominalCapacity = 21573.978761473172
}

# Liquid hydrogen
Import Vessel "bulk_carrier_capesize_ice_liquid_hydrogen"
Vessel "bulk_carrier_capesize_ice_liquid_hydrogen" {
        Route=Route("singapore_rotterdam_bulk_carrier_capesize")
        NominalCapacity = 102190.38268173016
}

Import Vessel "bulk_carrier_panamax_ice_liquid_hydrogen"
Vessel "bulk_carrier_panamax_ice_liquid_hydrogen" {
        Route=Route("singapore_rotterdam_bulk_carrier_panamax")
        NominalCapacity = 39568.95844340046
}

Import Vessel "bulk_carrier_handy_ice_liquid_hydrogen"
Vessel "bulk_carrier_handy_ice_liquid_hydrogen" {
        Route=Route("singapore_rotterdam_bulk_carrier_handy")
        NominalCapacity = 1.0
}

# Ammonia
Import Vessel "bulk_carrier_capesize_ice_ammonia"
Vessel "bulk_carrier_capesize_ice_ammonia" {
        Route=Route("singapore_rotterdam_bulk_carrier_capesize")
        NominalCapacity = 128365.56658063084
}

Import Vessel "bulk_carrier_panamax_ice_ammonia"
Vessel "bulk_carrier_panamax_ice_ammonia" {
        Route=Route("singapore_rotterdam_bulk_carrier_panamax")
        NominalCapacity = 55478.56782353357
}

Import Vessel "bulk_carrier_handy_ice_ammonia"
Vessel "bulk_carrier_handy_ice_ammonia" {
        Route=Route("singapore_rotterdam_bulk_carrier_handy")
        NominalCapacity = 16522.523177286264
}

# Methanol
Import Vessel "bulk_carrier_capesize_ice_methanol"
Vessel "bulk_carrier_capesize_ice_methanol" {
        Route=Route("singapore_rotterdam_bulk_carrier_capesize")
        NominalCapacity = 132698.57214502685
}

Import Vessel "bulk_carrier_panamax_ice_methanol"
Vessel "bulk_carrier_panamax_ice_methanol" {
        Route=Route("singapore_rotterdam_bulk_carrier_panamax")
        NominalCapacity = 58027.416176561645
}

Import Vessel "bulk_carrier_handy_ice_methanol"
Vessel "bulk_carrier_handy_ice_methanol" {
        Route=Route("singapore_rotterdam_bulk_carrier_handy")
        NominalCapacity = 18475.353646040214
}

# FT diesel
Import Vessel "bulk_carrier_capesize_ice_FTdiesel"
Vessel "bulk_carrier_capesize_ice_FTdiesel" {
        Route=Route("singapore_rotterdam_bulk_carrier_capesize")
        NominalCapacity = 139741.85883622992
}

Import Vessel "bulk_carrier_panamax_ice_FTdiesel"
Vessel "bulk_carrier_panamax_ice_FTdiesel" {
        Route=Route("singapore_rotterdam_bulk_carrier_panamax")
        NominalCapacity = 61913.724937707535
}

Import Vessel "bulk_carrier_handy_ice_FTdiesel"
Vessel "bulk_carrier_handy_ice_FTdiesel" {
        Route=Route("singapore_rotterdam_bulk_carrier_handy")
        NominalCapacity = 21419.991691055973
}

# Methane
Import Vessel "bulk_carrier_capesize_ice_methane"
Vessel "bulk_carrier_capesize_ice_methane" {
        Route=Route("singapore_rotterdam_bulk_carrier_capesize")
        NominalCapacity = 134865.1809056272
}

Import Vessel "bulk_carrier_panamax_ice_methane"
Vessel "bulk_carrier_panamax_ice_methane" {
        Route=Route("singapore_rotterdam_bulk_carrier_panamax")
        NominalCapacity = 59369.038826797136
}

Import Vessel "bulk_carrier_handy_ice_methane"
Vessel "bulk_carrier_handy_ice_methane" {
        Route=Route("singapore_rotterdam_bulk_carrier_handy")
        NominalCapacity = 19321.736324303154
}

############################# Container ships ###################################
 
# LSFO
Import Vessel "container_8000_teu_ice_oil"
Vessel "container_8000_teu_ice_oil" {
        Route=Route("singapore_rotterdam_container_8000_teu")
        NominalCapacity = 8000.0
}

Import Vessel "container_3500_teu_ice_oil"
Vessel "container_3500_teu_ice_oil" {
        Route=Route("singapore_rotterdam_container_3500_teu")
        NominalCapacity = 3500.0
}

# Liquid hydrogen
Import Vessel "container_8000_teu_ice_liquid_hydrogen"
Vessel "container_8000_teu_ice_liquid_hydrogen" {
        Route=Route("singapore_rotterdam_container_8000_teu")
        NominalCapacity = 5418.0980768967065
}

Import Vessel "container_3500_teu_ice_liquid_hydrogen"
Vessel "container_3500_teu_ice_liquid_hydrogen" {
        Route=Route("singapore_rotterdam_container_3500_teu")
        NominalCapacity = 2591.6366545695755
}

# Ammonia
Import Vessel "container_8000_teu_ice_ammonia"
Vessel "container_8000_teu_ice_ammonia" {
        Route=Route("singapore_rotterdam_container_8000_teu")
        NominalCapacity = 7109.007399345198
}

Import Vessel "container_3500_teu_ice_ammonia"
Vessel "container_3500_teu_ice_ammonia" {
        Route=Route("singapore_rotterdam_container_3500_teu")
        NominalCapacity = 3155.574392982704
}

# Methanol
Import Vessel "container_8000_teu_ice_methanol"
Vessel "container_8000_teu_ice_methanol" {
        Route=Route("singapore_rotterdam_container_8000_teu")
        NominalCapacity = 7438.1897830461985
}

Import Vessel "container_3500_teu_ice_methanol"
Vessel "container_3500_teu_ice_methanol" {
        Route=Route("singapore_rotterdam_container_3500_teu")
        NominalCapacity = 3281.5182489624103
}

# FT diesel
Import Vessel "container_8000_teu_ice_FTdiesel"
Vessel "container_8000_teu_ice_FTdiesel" {
        Route=Route("singapore_rotterdam_container_8000_teu")
        NominalCapacity = 7967.809531082906
}

Import Vessel "container_3500_teu_ice_FTdiesel"
Vessel "container_3500_teu_ice_FTdiesel" {
        Route=Route("singapore_rotterdam_container_3500_teu")
        NominalCapacity = 3487.481484310019
}

# Methane
Import Vessel "container_8000_teu_ice_methane"
Vessel "container_8000_teu_ice_methane" {
        Route=Route("singapore_rotterdam_container_8000_teu")
        NominalCapacity = 7570.740404227076
}

Import Vessel "container_3500_teu_ice_methane"
Vessel "container_3500_teu_ice_methane" {
        Route=Route("singapore_rotterdam_container_3500_teu")
        NominalCapacity = 3333.0657127549744
}

############################# Tankers ###################################

# LSFO
Import Vessel "tanker_100k_dwt_ice_oil"
Vessel "tanker_100k_dwt_ice_oil" {
        Route=Route("singapore_rotterdam_tanker_100k_dwt")
        NominalCapacity = 95241.20647996894
}

Import Vessel "tanker_35k_dwt_ice_oil"
Vessel "tanker_35k_dwt_ice_oil" {
        Route=Route("singapore_rotterdam_tanker_35k_dwt")
        NominalCapacity = 33334.422267989125
}

# Liquid hydrogen
Import Vessel "tanker_100k_dwt_ice_liquid_hydrogen"
Vessel "tanker_100k_dwt_ice_liquid_hydrogen" {
        Route=Route("singapore_rotterdam_tanker_100k_dwt")
        NominalCapacity = 73464.42463301281
}

Import Vessel "tanker_35k_dwt_ice_liquid_hydrogen"
Vessel "tanker_35k_dwt_ice_liquid_hydrogen" {
        Route=Route("singapore_rotterdam_tanker_35k_dwt")
        NominalCapacity = 1.0
}

# Ammonia
Import Vessel "tanker_100k_dwt_ice_ammonia"
Vessel "tanker_100k_dwt_ice_ammonia" {
        Route=Route("singapore_rotterdam_tanker_100k_dwt")
        NominalCapacity = 87358.52184507225
}

Import Vessel "tanker_35k_dwt_ice_ammonia"
Vessel "tanker_35k_dwt_ice_ammonia" {
        Route=Route("singapore_rotterdam_tanker_35k_dwt")
        NominalCapacity = 27432.4309768387
}

# Methanol
Import Vessel "tanker_100k_dwt_ice_methanol"
Vessel "tanker_100k_dwt_ice_methanol" {
        Route=Route("singapore_rotterdam_tanker_100k_dwt")
        NominalCapacity = 90266.34056283507
}

Import Vessel "tanker_35k_dwt_ice_methanol"
Vessel "tanker_35k_dwt_ice_methanol" {
        Route=Route("singapore_rotterdam_tanker_35k_dwt")
        NominalCapacity = 29947.634457764638
}

# FT diesel
Import Vessel "tanker_100k_dwt_ice_FTdiesel"
Vessel "tanker_100k_dwt_ice_FTdiesel" {
        Route=Route("singapore_rotterdam_tanker_100k_dwt")
        NominalCapacity = 95076.90667931123
}

Import Vessel "tanker_35k_dwt_ice_FTdiesel"
Vessel "tanker_35k_dwt_ice_FTdiesel" {
        Route=Route("singapore_rotterdam_tanker_35k_dwt")
        NominalCapacity = 33224.88906755066
}

# Methane
Import Vessel "tanker_100k_dwt_ice_methane"
Vessel "tanker_100k_dwt_ice_methane" {
        Route=Route("singapore_rotterdam_tanker_100k_dwt")
        NominalCapacity = 91866.95456526183
}

Import Vessel "tanker_35k_dwt_ice_methane"
Vessel "tanker_35k_dwt_ice_methane" {
        Route=Route("singapore_rotterdam_tanker_35k_dwt")
        NominalCapacity = 30986.333029322574
}
