############################# Bulk carriers ###################################

# FT diesel
Import Vessel "bulk_carrier_capesize_ice_FTdiesel"
Vessel "bulk_carrier_capesize_ice_FTdiesel" {
        NominalCapacity = 139741.85883622992
}

Import Vessel "bulk_carrier_panamax_ice_FTdiesel"
Vessel "bulk_carrier_panamax_ice_FTdiesel" {
        NominalCapacity = 61913.724937707535
}

Import Vessel "bulk_carrier_handy_ice_FTdiesel"
Vessel "bulk_carrier_handy_ice_FTdiesel" {
        NominalCapacity = 21419.991691055973
}

############################# Container ships ###################################
 
# FT diesel
Import Vessel "container_15000_teu_ice_FTdiesel"
Vessel "container_15000_teu_ice_FTdiesel" {
        NominalCapacity = 14946.349218471509
}

Import Vessel "container_8000_teu_ice_FTdiesel"
Vessel "container_8000_teu_ice_FTdiesel" {
        NominalCapacity = 7967.809531082906
}

Import Vessel "container_3500_teu_ice_FTdiesel"
Vessel "container_3500_teu_ice_FTdiesel" {
        NominalCapacity = 3487.481484310019
}

############################# Tankers ###################################

# FT diesel
Import Vessel "tanker_300k_dwt_ice_FTdiesel"
Vessel "tanker_300k_dwt_ice_FTdiesel" {
        NominalCapacity = 285285.486638153
}

Import Vessel "tanker_100k_dwt_ice_FTdiesel"
Vessel "tanker_100k_dwt_ice_FTdiesel" {
        NominalCapacity = 95076.90667931123
}

Import Vessel "tanker_35k_dwt_ice_FTdiesel"
Vessel "tanker_35k_dwt_ice_FTdiesel" {
        NominalCapacity = 33224.88906755066
}

######################### Gas Carriers ###########################

# FT diesel
Import Vessel "gas_carrier_100k_cbm_ice_FTdiesel"
Vessel "gas_carrier_100k_cbm_ice_FTdiesel" {
        NominalCapacity = 99726.16641107858
}
