############################# Bulk carriers ###################################

# Compressed hydrogen
Import Vessel "bulk_carrier_capesize_ice_compressed_hydrogen"
Vessel "bulk_carrier_capesize_ice_compressed_hydrogen" {
        EnforceMainFuelShare = TRUE
}

Import Vessel "bulk_carrier_panamax_ice_compressed_hydrogen"
Vessel "bulk_carrier_panamax_ice_compressed_hydrogen" {
        EnforceMainFuelShare = TRUE
}

Import Vessel "bulk_carrier_handy_ice_compressed_hydrogen"
Vessel "bulk_carrier_handy_ice_compressed_hydrogen" {
        EnforceMainFuelShare = TRUE
}

############################# Container ships ###################################

# Compressed hydrogen
Import Vessel "container_15000_teu_ice_compressed_hydrogen"
Vessel "container_15000_teu_ice_compressed_hydrogen" {
        EnforceMainFuelShare = TRUE
}

Import Vessel "container_8000_teu_ice_compressed_hydrogen"
Vessel "container_8000_teu_ice_compressed_hydrogen" {
        EnforceMainFuelShare = TRUE
}

Import Vessel "container_3500_teu_ice_compressed_hydrogen"
Vessel "container_3500_teu_ice_compressed_hydrogen" {
        EnforceMainFuelShare = TRUE
}

############################# Tankers ###################################

# Compressed hydrogen
Import Vessel "tanker_300k_dwt_ice_compressed_hydrogen"
Vessel "tanker_300k_dwt_ice_compressed_hydrogen" {
        EnforceMainFuelShare = TRUE
}

Import Vessel "tanker_100k_dwt_ice_compressed_hydrogen"
Vessel "tanker_100k_dwt_ice_compressed_hydrogen" {
        EnforceMainFuelShare = TRUE
}

Import Vessel "tanker_35k_dwt_ice_compressed_hydrogen"
Vessel "tanker_35k_dwt_ice_compressed_hydrogen" {
        EnforceMainFuelShare = TRUE
}

######################### Gas Carriers ###########################

# Compressed hydrogen
Import Vessel "gas_carrier_100k_cbm_ice_compressed_hydrogen"
Vessel "gas_carrier_100k_cbm_ice_compressed_hydrogen" {
        EnforceMainFuelShare = TRUE
}
