############################# Bulk carriers ###################################

# Methane
Import Vessel "bulk_carrier_capesize_ice_methane"
Vessel "bulk_carrier_capesize_ice_methane" {
        NominalCapacity = 134865.1809056272
        EnforceMainFuelShare = TRUE
}

Import Vessel "bulk_carrier_panamax_ice_methane"
Vessel "bulk_carrier_panamax_ice_methane" {
        NominalCapacity = 59369.038826797136
        EnforceMainFuelShare = TRUE
}

Import Vessel "bulk_carrier_handy_ice_methane"
Vessel "bulk_carrier_handy_ice_methane" {
        NominalCapacity = 19321.736324303154
        EnforceMainFuelShare = TRUE
}

############################# Container ships ###################################

# Methane
Import Vessel "container_15000_teu_ice_methane"
Vessel "container_15000_teu_ice_methane" {
        NominalCapacity = 14284.567340378464
        EnforceMainFuelShare = TRUE
}

Import Vessel "container_8000_teu_ice_methane"
Vessel "container_8000_teu_ice_methane" {
        NominalCapacity = 7570.740404227076
        EnforceMainFuelShare = TRUE
}

Import Vessel "container_3500_teu_ice_methane"
Vessel "container_3500_teu_ice_methane" {
        NominalCapacity = 3333.0657127549744
        EnforceMainFuelShare = TRUE
}

############################# Tankers ###################################

# Methane
Import Vessel "tanker_300k_dwt_ice_methane"
Vessel "tanker_300k_dwt_ice_methane" {
        NominalCapacity = 276783.24525624095
        EnforceMainFuelShare = TRUE
}

Import Vessel "tanker_100k_dwt_ice_methane"
Vessel "tanker_100k_dwt_ice_methane" {
        NominalCapacity = 91866.95456526183
        EnforceMainFuelShare = TRUE
}

Import Vessel "tanker_35k_dwt_ice_methane"
Vessel "tanker_35k_dwt_ice_methane" {
        NominalCapacity = 30986.333029322574
        EnforceMainFuelShare = TRUE
}

######################### Gas Carriers ###########################

# Methane
Import Vessel "gas_carrier_100k_cbm_ice_methane"
Vessel "gas_carrier_100k_cbm_ice_methane" {
        NominalCapacity = 96348.43170529167
        EnforceMainFuelShare = TRUE
}
