############################# Bulk carriers ###################################

# LSFO
Import Vessel "bulk_carrier_capesize_ice_oil"
Vessel "bulk_carrier_capesize_ice_oil" {
        Route=Route("singapore_rotterdam_bulk_carrier_capesize")
}

Import Vessel "bulk_carrier_panamax_ice_oil"
Vessel "bulk_carrier_panamax_ice_oil" {
        Route=Route("singapore_rotterdam_bulk_carrier_panamax")
}

Import Vessel "bulk_carrier_handy_ice_oil"
Vessel "bulk_carrier_handy_ice_oil" {
        Route=Route("singapore_rotterdam_bulk_carrier_handy")
}

# Liquid hydrogen
Import Vessel "bulk_carrier_capesize_ice_liquid_hydrogen"
Vessel "bulk_carrier_capesize_ice_liquid_hydrogen" {
        Route=Route("singapore_rotterdam_bulk_carrier_capesize")
}

Import Vessel "bulk_carrier_panamax_ice_liquid_hydrogen"
Vessel "bulk_carrier_panamax_ice_liquid_hydrogen" {
        Route=Route("singapore_rotterdam_bulk_carrier_panamax")
}

Import Vessel "bulk_carrier_handy_ice_liquid_hydrogen"
Vessel "bulk_carrier_handy_ice_liquid_hydrogen" {
        Route=Route("singapore_rotterdam_bulk_carrier_handy")
}

# Ammonia
Import Vessel "bulk_carrier_capesize_ice_ammonia"
Vessel "bulk_carrier_capesize_ice_ammonia" {
        Route=Route("singapore_rotterdam_bulk_carrier_capesize")
}

Import Vessel "bulk_carrier_panamax_ice_ammonia"
Vessel "bulk_carrier_panamax_ice_ammonia" {
        Route=Route("singapore_rotterdam_bulk_carrier_panamax")
}

Import Vessel "bulk_carrier_handy_ice_ammonia"
Vessel "bulk_carrier_handy_ice_ammonia" {
        Route=Route("singapore_rotterdam_bulk_carrier_handy")
}

# Methanol
Import Vessel "bulk_carrier_capesize_ice_methanol"
Vessel "bulk_carrier_capesize_ice_methanol" {
        Route=Route("singapore_rotterdam_bulk_carrier_capesize")
}

Import Vessel "bulk_carrier_panamax_ice_methanol"
Vessel "bulk_carrier_panamax_ice_methanol" {
        Route=Route("singapore_rotterdam_bulk_carrier_panamax")
}

Import Vessel "bulk_carrier_handy_ice_methanol"
Vessel "bulk_carrier_handy_ice_methanol" {
        Route=Route("singapore_rotterdam_bulk_carrier_handy")
}

# FT diesel
Import Vessel "bulk_carrier_capesize_ice_FTdiesel"
Vessel "bulk_carrier_capesize_ice_FTdiesel" {
        Route=Route("singapore_rotterdam_bulk_carrier_capesize")
}

Import Vessel "bulk_carrier_panamax_ice_FTdiesel"
Vessel "bulk_carrier_panamax_ice_FTdiesel" {
        Route=Route("singapore_rotterdam_bulk_carrier_panamax")
}

Import Vessel "bulk_carrier_handy_ice_FTdiesel"
Vessel "bulk_carrier_handy_ice_FTdiesel" {
        Route=Route("singapore_rotterdam_bulk_carrier_handy")
}

# Methane
Import Vessel "bulk_carrier_capesize_ice_methane"
Vessel "bulk_carrier_capesize_ice_methane" {
        Route=Route("singapore_rotterdam_bulk_carrier_capesize")
}

Import Vessel "bulk_carrier_panamax_ice_methane"
Vessel "bulk_carrier_panamax_ice_methane" {
        Route=Route("singapore_rotterdam_bulk_carrier_panamax")
}

Import Vessel "bulk_carrier_handy_ice_methane"
Vessel "bulk_carrier_handy_ice_methane" {
        Route=Route("singapore_rotterdam_bulk_carrier_handy")
}

############################# Container ships ###################################
 
# LSFO
Import Vessel "container_8000_teu_ice_oil"
Vessel "container_8000_teu_ice_oil" {
        Route=Route("singapore_rotterdam_container_8000_teu")
}

Import Vessel "container_3500_teu_ice_oil"
Vessel "container_3500_teu_ice_oil" {
        Route=Route("singapore_rotterdam_container_3500_teu")
}

# Liquid hydrogen
Import Vessel "container_8000_teu_ice_liquid_hydrogen"
Vessel "container_8000_teu_ice_liquid_hydrogen" {
        Route=Route("singapore_rotterdam_container_8000_teu")
}

Import Vessel "container_3500_teu_ice_liquid_hydrogen"
Vessel "container_3500_teu_ice_liquid_hydrogen" {
        Route=Route("singapore_rotterdam_container_3500_teu")
}

# Ammonia
Import Vessel "container_8000_teu_ice_ammonia"
Vessel "container_8000_teu_ice_ammonia" {
        Route=Route("singapore_rotterdam_container_8000_teu")
}

Import Vessel "container_3500_teu_ice_ammonia"
Vessel "container_3500_teu_ice_ammonia" {
        Route=Route("singapore_rotterdam_container_3500_teu")
}

# Methanol
Import Vessel "container_8000_teu_ice_methanol"
Vessel "container_8000_teu_ice_methanol" {
        Route=Route("singapore_rotterdam_container_8000_teu")
}

Import Vessel "container_3500_teu_ice_methanol"
Vessel "container_3500_teu_ice_methanol" {
        Route=Route("singapore_rotterdam_container_3500_teu")
}

# FT diesel
Import Vessel "container_8000_teu_ice_FTdiesel"
Vessel "container_8000_teu_ice_FTdiesel" {
        Route=Route("singapore_rotterdam_container_8000_teu")
}

Import Vessel "container_3500_teu_ice_FTdiesel"
Vessel "container_3500_teu_ice_FTdiesel" {
        Route=Route("singapore_rotterdam_container_3500_teu")
}

# Methane
Import Vessel "container_8000_teu_ice_methane"
Vessel "container_8000_teu_ice_methane" {
        Route=Route("singapore_rotterdam_container_8000_teu")
}

Import Vessel "container_3500_teu_ice_methane"
Vessel "container_3500_teu_ice_methane" {
        Route=Route("singapore_rotterdam_container_3500_teu")
}

############################# Tankers ###################################

# LSFO
Import Vessel "tanker_100k_dwt_ice_oil"
Vessel "tanker_100k_dwt_ice_oil" {
        Route=Route("singapore_rotterdam_tanker_100k_dwt")
}

Import Vessel "tanker_35k_dwt_ice_oil"
Vessel "tanker_35k_dwt_ice_oil" {
        Route=Route("singapore_rotterdam_tanker_35k_dwt")
}

# Liquid hydrogen
Import Vessel "tanker_100k_dwt_ice_liquid_hydrogen"
Vessel "tanker_100k_dwt_ice_liquid_hydrogen" {
        Route=Route("singapore_rotterdam_tanker_100k_dwt")
}

Import Vessel "tanker_35k_dwt_ice_liquid_hydrogen"
Vessel "tanker_35k_dwt_ice_liquid_hydrogen" {
        Route=Route("singapore_rotterdam_tanker_35k_dwt")
}

# Ammonia
Import Vessel "tanker_100k_dwt_ice_ammonia"
Vessel "tanker_100k_dwt_ice_ammonia" {
        Route=Route("singapore_rotterdam_tanker_100k_dwt")
}

Import Vessel "tanker_35k_dwt_ice_ammonia"
Vessel "tanker_35k_dwt_ice_ammonia" {
        Route=Route("singapore_rotterdam_tanker_35k_dwt")
}

# Methanol
Import Vessel "tanker_100k_dwt_ice_methanol"
Vessel "tanker_100k_dwt_ice_methanol" {
        Route=Route("singapore_rotterdam_tanker_100k_dwt")
}

Import Vessel "tanker_35k_dwt_ice_methanol"
Vessel "tanker_35k_dwt_ice_methanol" {
        Route=Route("singapore_rotterdam_tanker_35k_dwt")
}

# FT diesel
Import Vessel "tanker_100k_dwt_ice_FTdiesel"
Vessel "tanker_100k_dwt_ice_FTdiesel" {
        Route=Route("singapore_rotterdam_tanker_100k_dwt")
}

Import Vessel "tanker_35k_dwt_ice_FTdiesel"
Vessel "tanker_35k_dwt_ice_FTdiesel" {
        Route=Route("singapore_rotterdam_tanker_35k_dwt")
}

# Methane
Import Vessel "tanker_100k_dwt_ice_methane"
Vessel "tanker_100k_dwt_ice_methane" {
        Route=Route("singapore_rotterdam_tanker_100k_dwt")
}

Import Vessel "tanker_35k_dwt_ice_methane"
Vessel "tanker_35k_dwt_ice_methane" {
        Route=Route("singapore_rotterdam_tanker_35k_dwt")
}
