############################# Bulk carriers ###################################

# LSFO
Import Vessel "bulk_carrier_capesize_ice_oil"
Vessel "bulk_carrier_capesize_ice_oil" {
        NominalCapacity = 140077.8522122301
}

Import Vessel "bulk_carrier_panamax_ice_oil"
Vessel "bulk_carrier_panamax_ice_oil" {
        NominalCapacity = 62001.708506750336
}

Import Vessel "bulk_carrier_handy_ice_oil"
Vessel "bulk_carrier_handy_ice_oil" {
        NominalCapacity = 21573.978761473172
}

############################# Container ships ###################################
 
# LSFO
Import Vessel "container_15000_teu_ice_oil"
Vessel "container_15000_teu_ice_oil" {
        NominalCapacity = 15000.0
}

Import Vessel "container_8000_teu_ice_oil"
Vessel "container_8000_teu_ice_oil" {
        NominalCapacity = 8000.0
}

Import Vessel "container_3500_teu_ice_oil"
Vessel "container_3500_teu_ice_oil" {
        NominalCapacity = 3500.0
}

############################# Tankers ###################################

# LSFO
Import Vessel "tanker_300k_dwt_ice_oil"
Vessel "tanker_300k_dwt_ice_oil" {
        NominalCapacity = 285723.6194399068
}

Import Vessel "tanker_100k_dwt_ice_oil"
Vessel "tanker_100k_dwt_ice_oil" {
        NominalCapacity = 95241.20647996894
}

Import Vessel "tanker_35k_dwt_ice_oil"
Vessel "tanker_35k_dwt_ice_oil" {
        NominalCapacity = 33334.422267989125
}

######################### Gas Carriers ###########################

# LSFO
Import Vessel "gas_carrier_100k_cbm_ice_oil"
Vessel "gas_carrier_100k_cbm_ice_oil" {
        NominalCapacity = 100000.0
}
