############################# Bulk carriers ###################################

# Methane
Import Vessel "bulk_carrier_capesize_ice_methane"
Vessel "bulk_carrier_capesize_ice_methane" {
        EnforceMainFuelShare = TRUE
}

Import Vessel "bulk_carrier_panamax_ice_methane"
Vessel "bulk_carrier_panamax_ice_methane" {
        EnforceMainFuelShare = TRUE
}

Import Vessel "bulk_carrier_handy_ice_methane"
Vessel "bulk_carrier_handy_ice_methane" {
        EnforceMainFuelShare = TRUE
}

############################# Container ships ###################################

# Methane
Import Vessel "container_15000_teu_ice_methane"
Vessel "container_15000_teu_ice_methane" {
        EnforceMainFuelShare = TRUE
}

Import Vessel "container_8000_teu_ice_methane"
Vessel "container_8000_teu_ice_methane" {
        EnforceMainFuelShare = TRUE
}

Import Vessel "container_3500_teu_ice_methane"
Vessel "container_3500_teu_ice_methane" {
        EnforceMainFuelShare = TRUE
}

############################# Tankers ###################################

# Methane
Import Vessel "tanker_300k_dwt_ice_methane"
Vessel "tanker_300k_dwt_ice_methane" {
        EnforceMainFuelShare = TRUE
}

Import Vessel "tanker_100k_dwt_ice_methane"
Vessel "tanker_100k_dwt_ice_methane" {
        EnforceMainFuelShare = TRUE
}

Import Vessel "tanker_35k_dwt_ice_methane"
Vessel "tanker_35k_dwt_ice_methane" {
        EnforceMainFuelShare = TRUE
}

######################### Gas Carriers ###########################

# Methane
Import Vessel "gas_carrier_100k_cbm_ice_methane"
Vessel "gas_carrier_100k_cbm_ice_methane" {
        EnforceMainFuelShare = TRUE
}
