############################# Bulk carriers ###################################

# Liquid hydrogen
Import Vessel "bulk_carrier_capesize_ice_liquid_hydrogen"
Vessel "bulk_carrier_capesize_ice_liquid_hydrogen" {
        NominalCapacity = 106253.7448370028
        EnforceMainFuelShare = TRUE
}

Import Vessel "bulk_carrier_panamax_ice_liquid_hydrogen"
Vessel "bulk_carrier_panamax_ice_liquid_hydrogen" {
        NominalCapacity = 36777.19825084145
        EnforceMainFuelShare = TRUE
}

Import Vessel "bulk_carrier_handy_ice_liquid_hydrogen"
Vessel "bulk_carrier_handy_ice_liquid_hydrogen" {
        NominalCapacity = 1.0
        EnforceMainFuelShare = TRUE
}

############################# Container ships ###################################

# Liquid hydrogen
Import Vessel "container_15000_teu_ice_liquid_hydrogen"
Vessel "container_15000_teu_ice_liquid_hydrogen" {
        NominalCapacity = 10343.159611575606
        EnforceMainFuelShare = TRUE
}

Import Vessel "container_8000_teu_ice_liquid_hydrogen"
Vessel "container_8000_teu_ice_liquid_hydrogen" {
        NominalCapacity = 5853.923412859924
        EnforceMainFuelShare = TRUE
}

Import Vessel "container_3500_teu_ice_liquid_hydrogen"
Vessel "container_3500_teu_ice_liquid_hydrogen" {
        NominalCapacity = 2492.561219859963
        EnforceMainFuelShare = TRUE
}

############################# Tankers ###################################

# Liquid hydrogen
Import Vessel "tanker_300k_dwt_ice_liquid_hydrogen"
Vessel "tanker_300k_dwt_ice_liquid_hydrogen" {
        NominalCapacity = 223704.76613180598
        EnforceMainFuelShare = TRUE
}

Import Vessel "tanker_100k_dwt_ice_liquid_hydrogen"
Vessel "tanker_100k_dwt_ice_liquid_hydrogen" {
        NominalCapacity = 71670.26336683944
        EnforceMainFuelShare = TRUE
}

Import Vessel "tanker_35k_dwt_ice_liquid_hydrogen"
Vessel "tanker_35k_dwt_ice_liquid_hydrogen" {
        NominalCapacity = 1.0
        EnforceMainFuelShare = TRUE
}

######################### Gas Carriers ###########################

# Liquid hydrogen
Import Vessel "gas_carrier_100k_cbm_ice_liquid_hydrogen"
Vessel "gas_carrier_100k_cbm_ice_liquid_hydrogen" {
        NominalCapacity = 86225.0105736733
        EnforceMainFuelShare = TRUE
}
