############################# Bulk carriers ###################################

# Methanol
Import Vessel "bulk_carrier_capesize_ice_methanol"
Vessel "bulk_carrier_capesize_ice_methanol" {
        EnforceMainFuelShare = TRUE
}

Import Vessel "bulk_carrier_panamax_ice_methanol"
Vessel "bulk_carrier_panamax_ice_methanol" {
        EnforceMainFuelShare = TRUE
}

Import Vessel "bulk_carrier_handy_ice_methanol"
Vessel "bulk_carrier_handy_ice_methanol" {
        EnforceMainFuelShare = TRUE
}

############################# Container ships ###################################

# Methanol
Import Vessel "container_15000_teu_ice_methanol"
Vessel "container_15000_teu_ice_methanol" {
        EnforceMainFuelShare = TRUE
}

Import Vessel "container_8000_teu_ice_methanol"
Vessel "container_8000_teu_ice_methanol" {
        EnforceMainFuelShare = TRUE
}

Import Vessel "container_3500_teu_ice_methanol"
Vessel "container_3500_teu_ice_methanol" {
        EnforceMainFuelShare = TRUE
}

############################# Tankers ###################################

# Methanol
Import Vessel "tanker_300k_dwt_ice_methanol"
Vessel "tanker_300k_dwt_ice_methanol" {
        EnforceMainFuelShare = TRUE
}

Import Vessel "tanker_100k_dwt_ice_methanol"
Vessel "tanker_100k_dwt_ice_methanol" {
        EnforceMainFuelShare = TRUE
}

Import Vessel "tanker_35k_dwt_ice_methanol"
Vessel "tanker_35k_dwt_ice_methanol" {
        EnforceMainFuelShare = TRUE
}

######################### Gas Carriers ###########################

# Methanol
Import Vessel "gas_carrier_100k_cbm_ice_methanol"
Vessel "gas_carrier_100k_cbm_ice_methanol" {
        EnforceMainFuelShare = TRUE
}
