############################# Bulk carriers ###################################

# Ammonia
Import Vessel "bulk_carrier_capesize_ice_ammonia"
Vessel "bulk_carrier_capesize_ice_ammonia" {
        NominalCapacity = 128446.85672208662
        EnforceMainFuelShare = TRUE
}

Import Vessel "bulk_carrier_panamax_ice_ammonia"
Vessel "bulk_carrier_panamax_ice_ammonia" {
        NominalCapacity = 55432.113651906766
        EnforceMainFuelShare = TRUE
}

Import Vessel "bulk_carrier_handy_ice_ammonia"
Vessel "bulk_carrier_handy_ice_ammonia" {
        NominalCapacity = 16476.821926133485
        EnforceMainFuelShare = TRUE
}

############################# Container ships ###################################

# Ammonia
Import Vessel "container_15000_teu_ice_ammonia"
Vessel "container_15000_teu_ice_ammonia" {
        NominalCapacity = 13507.974735747588
        EnforceMainFuelShare = TRUE
}

Import Vessel "container_8000_teu_ice_ammonia"
Vessel "container_8000_teu_ice_ammonia" {
        NominalCapacity = 7118.813653865916
        EnforceMainFuelShare = TRUE
}

Import Vessel "container_3500_teu_ice_ammonia"
Vessel "container_3500_teu_ice_ammonia" {
        NominalCapacity = 3153.433460024702
        EnforceMainFuelShare = TRUE
}

############################# Tankers ###################################

# Ammonia
Import Vessel "tanker_300k_dwt_ice_ammonia"
Vessel "tanker_300k_dwt_ice_ammonia" {
        NominalCapacity = 264702.7917410164
        EnforceMainFuelShare = TRUE
}

Import Vessel "tanker_100k_dwt_ice_ammonia"
Vessel "tanker_100k_dwt_ice_ammonia" {
        NominalCapacity = 87322.10438702288
        EnforceMainFuelShare = TRUE
}

Import Vessel "tanker_35k_dwt_ice_ammonia"
Vessel "tanker_35k_dwt_ice_ammonia" {
        NominalCapacity = 27398.068124250793
        EnforceMainFuelShare = TRUE
}

######################### Gas Carriers ###########################

# Ammonia
Import Vessel "gas_carrier_100k_cbm_ice_ammonia"
Vessel "gas_carrier_100k_cbm_ice_ammonia" {
        NominalCapacity = 92629.35257688032
        EnforceMainFuelShare = TRUE
}
