# Definition of cost and emissions for hydrogen from United States for pathway SMR_H_renewable_E

Port "Australia" {
    
# Emissions
set_bunker_WTT_overwrite("hydrogen", "carbon_dioxide", 28.01549241018001)

# Costs
set_bunker_price_overwrite("hydrogen", 9918.629641351668)

}

Port "Japan" {
    
# Emissions
set_bunker_WTT_overwrite("hydrogen", "carbon_dioxide", 13.67605093976)

# Costs
set_bunker_price_overwrite("hydrogen", 13160.510055664286)

}

Port "United States" {
    
# Emissions
set_bunker_WTT_overwrite("hydrogen", "carbon_dioxide", 5.0009440003600005)

# Costs
set_bunker_price_overwrite("hydrogen", 6600.105502391394)

}
